# Generated by Django 2.2.3 on 2019-07-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='objectionname',
            new_name='regionname',
        ),
    ]
