# Generated by Django 2.2.3 on 2019-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190730_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='commons.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='commons.Target'),
        ),
    ]
