# Generated by Django 2.2.3 on 2019-07-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190729_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activityname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regionname',
            new_name='name',
        ),
    ]
