# Generated by Django 2.2.3 on 2019-07-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20190730_0421'),
        ('account', '0009_auto_20190730_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.Region'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
