# Generated by Django 2.2.3 on 2019-07-30 13:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('account', '0003_auto_20190730_2244'),
        ('review', '0003_auto_20190730_2244'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Target',
        ),
    ]
