# Generated by Django 2.2.3 on 2019-07-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='activity',
        ),
        migrations.AddField(
            model_name='review',
            name='activity',
            field=models.ManyToManyField(null=True, related_name='reivews', to='commons.Activity'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='region',
        ),
        migrations.AddField(
            model_name='review',
            name='region',
            field=models.ManyToManyField(null=True, related_name='reivews', to='commons.Region'),
        ),
    ]
