# Generated by Django 2.2.3 on 2019-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='reivews',
            new_name='review',
        ),
    ]
