# Generated by Django 2.2.3 on 2019-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190730_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='region2',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
