# Generated by Django 2.2.3 on 2019-08-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190802_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='review.Review'),
        ),
    ]
