# Generated by Django 2.2.3 on 2019-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
