# Generated by Django 2.2.3 on 2019-07-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20190729_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
